version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: tccrh_frontend
    environment:
      - NODE_ENV=production
    # Se precisar conectar com backend local, ajuste a seguir:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"